import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { mulish } from "./_lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mulish.className} dark p-6 antialiased`}
      >
        <ClerkProvider appearance={{
          baseTheme: dark
        }}>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
